### ISSUE TITLE
Rewrite dataframe display fns / conversions

### ISSUE THREAD

**Issue by vidma** [spark-notebook/spark-notebook#604]
- [ ] some of DataFrame to Seq implicits, or some `table` widget(s) need to be rewritten from scratch.
- [ ] DataFrameWidget prints the wrong value when two columns have the same name #612 
- [ ] make widgets in tabs to bind to the same observable #605
- [ ] make tabs lazy #605
- [ ] make sure display & other widgets DO NOT cache data frame #621
- [x] when SQL query returns 0 rows, the `display` fn crashes
- [ ] there should not be two different `table(df)` display fns
  - now we have `table` [used by `display` & another one which shows up when cell returns a value

![pasted image at 2016_03_08 10_55](https://cloud.githubusercontent.com/assets/213426/13596790/61453efe-e51d-11e5-839d-8143815b5111.png)

cc @andypetrella @meh-ninja
